### PR TITLE
Booking step3 - DetailsForm & UserDetails

### PR DESCRIPTION
**Pull request by solidtop**
- Added 2 menus/components for displaying either user details or a details form.
- Email is added to bookingDetails (via onBlur event) and gets sent to server API every time handleUpdate() function runs. 
- Basic client validation on email 
- Updated some type names and general cleanup from last PR because it haunted me at night.
- Added ErrorMessage to display errors from server.

details-form
user-details
error-message

### CODE REVIEW

**Review by yvette809 — APPROVED** [review]
Nice addition to the existing page. I love how you organised all the files and made it easy to follow up

**Comment by yvette809** [comment]
It's quite easy to create a modal.
Create a modal state in the detailsForm component like this : const[modal, setModal] and = useState (false)
Attach an onclick even to the login button and set the modal state to true on click.

Create a Modal component and pass the setShowModal to it as prop. This setShowModal will be able to close the modal in the modal component by setting it back to false upon click.The modal component is where you will have your login form 

In the detailsForm component, you conditional render the Modal i.e it will only show when the showModal state is true. Something like this {showModal && <Modal setShowMadal ={setShowModal} />

**Comment by yvette809** [comment]
{showModal && <Modal setShowModal ={setShowModal} />

**Comment by solidtop** [comment]
> 



> It's quite easy to create a modal. Create a modal state in the detailsForm component like this : const[modal, setModal] and = useState (false) Attach an onclick even to the login button and set the modal state to true on click.
> 
> Create a Modal component and pass the setShowModal to it as prop. This setShowModal will be able to close the modal in the modal component by setting it back to false upon click.The modal component is where you will have your login form
> 
> In the detailsForm component, you conditional render the Modal i.e it will only show when the showModal state is true. Something like this {showModal &&

That sounds like the best solution! I will try and implement this before merging then :) Thanks!

**Pull request merged**
